alias yeet="yay -Rnsu"
alias vim=nvim
alias vi=nvim
alias v=nvim
alias cat="bat --color always --plain"
alias ls='eza -lh --group-directories-first'
alias ll="ls -l"
alias la="ls -al"
alias lt="ls --tree"
alias mv="mv -v"
alias mkdir="mkdir -v"
alias cp="cp -vr"
alias rm="rm -vr"
alias cw="change-wallpaper.sh"
alias ..="cd .."
alias ...='cd ../..'
alias ....='cd ../../..'
alias pnpx="pnpm dlx"
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
